version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    image: local/zookeeper:3.1.0
    restart: always
    build:
      context: ./zookeeper
    volumes:
      - './zookeeper/zookeeper.properties:/kafka/config/zookeeper.properties'
      - './zookeeper/data/zookeeper/:/tmp/zookeeper/'
    ports:
      - 2181:2181
    networks:
      - kafka  
  kafka:
    container_name: kafka
    image: local/kafka:3.1.0
    restart: always
    build: 
      context: ./kafka
    volumes:
      - './kafka/server.properties:/kafka/config/server.properties'
      - './kafka/data/kafka/:/tmp/kafka-logs/'
    ports:
      - 9092:9092
    networks:
      - kafka  
networks: 
  kafka:
    name: kafka